#
# sudo dnf install npm clang-tools-extra
# sudo dnf install python3-devel python3-flake8 python3-yapf python3-isort
# 

[options]
automatic_update = true

# Theming
colorscheme = 'neodark'
enable_guicolors = true
statusline_unicode_symbols = false
custom_color_palette = [     
    ['#d7ffaf', '#5F875F', 193, 65],
    ['#ffffff', '#373b41', 231, 22],
    ['#ffffff', '#282a2e', 231, 237],
    ['#4e4e4e', 239],
    ['#c5c8c6', '#405170', 193, 110],
    ['#c5c8c6', '#cc6666', 231, 167],
    ['#d7d7ff', '#5f5f87', 88, 0],
    ['#ffffff', '#689d6a', 231, 72],
    ['#ffffff', '#8f3f71', 231, 132],
]

# Display absolute line numbers
relativenumber = false

# Indentation and line length
max_column = 80
default_indent = 8
expand_tab = false

filemanager = 'defx'
disabled_plugins = ['deoplete-go']

# Custom vimscript options 
bootstrap_before = 'user#apply'
bootstrap_after = 'user#apply'

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = 'complete'
auto-completion-tab-key-behavior = 'smart'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'default'

[[layers]]
name = 'denite'

#
# Version control
#

[[layers]]
name = 'git'

[[layers]]
name = 'github'

#
# Language support
#

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#csharp'

[[layers]]
name = 'lang#extra'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#vim'

[[custom_plugins]]
name = 'KeitaNakamura/neodark.vim'
merged = false

[[custom_plugins]]
name = 'Raimondi/YAIFA'
merged = false

[[custom_plugins]]
name = 'igankevich/mesonic'
merged = false
