#!/bin/sh

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:StollD/dotfiles.git"

git clone https://github.com/syl20bnr/spacemacs ~/.config/emacs
ln -s ~/.config/emacs ~/.emacs.d
